# TRMNLP configuration
# {{ env.VARIABLE }} interpolation is available here
---
# auto-reload when files change (`watch: false` to disable)
watch:
  - .trmnlp.yml
  - src

# values of custom fields (defined in src/settings.yml)
custom_fields: {
  show_notes: 'yes',
  show_list_names: 'no'
}

# override variables
variables:
  trmnl: { plugin_settings: { instance_name: 'Reminders'  } }
  all: [
    {
      "c": "Yes",
      "d": "",
      "f": false,
      "l": "Personal",
      "n": "Recently completed",
      "o": "",
      "p": "None",
      "t": ""
    },
    {
      "c": "Yes",
      "d": "",
      "f": true,
      "l": "Personal",
      "n": "Recently completed - Flagged!",
      "o": "",
      "p": "None",
      "t": ""
    },
    {
      "c": "No",
      "d": "",
      "f": false,
      "l": "Personal",
      "n": "Fill in passport form",
      "o": "",
      "p": "None",
      "t": ""
    },
    {
      "c": "No",
      "d": "2025-05-04",
      "f": false,
      "l": "Personal",
      "n": "Book a vet appointment for Pepper",
      "o": "",
      "p": "None",
      "t": ""
    },
    {
      "c": "No",
      "d": "",
      "f": false,
      "l": "Personal",
      "n": "Buy a birthday present for Niko",
      "o": "",
      "p": "None",
      "t": ""
    },
    {
      "c": "No",
      "d": "",
      "f": false,
      "l": "Personal",
      "n": "Get slippers for Niko",
      "o": "Size 22",
      "p": "None",
      "t": ""
    },
    {
      "c": "No",
      "d": "",
      "f": false,
      "l": "Personal",
      "n": "Book in a hot air balloon ride with mama and Nico",
      "o": "",
      "p": "None",
      "t": ""
    },
    {
      "c": "No",
      "d": "",
      "f": false,
      "l": "Personal",
      "n": "Get gloves for Niko",
      "o": "",
      "p": "None",
      "t": ""
    },
    {
      "c": "No",
      "d": "",
      "f": false,
      "l": "Personal",
      "n": "Get gloves for Niko",
      "o": "",
      "p": "None",
      "t": ""
      },
      {
        "c": "No",
        "d": "",
        "f": false,
        "l": "Personal",
        "n": "Get gloves for Niko",
        "o": "fooooooooooooooooooooooooo",
        "p": "None",
        "t": ""
      },
      {
        "c": "No",
        "d": "",
        "f": false,
        "l": "Personal",
        "n": "Get gloves for Niko",
        "o": "fooooooooooooooooooooooooo",
        "p": "None",
        "t": ""
      },
      {
        "c": "No",
        "d": "",
        "f": false,
        "l": "Personal",
        "n": "Get gloves for Niko",
        "o": "fooooooooooooooooooooooooo",
        "p": "None",
        "t": ""
      },
      {
        "c": "No",
        "d": "",
        "f": false,
        "l": "Personal",
        "n": "Get gloves for Niko",
        "o": "fooooooooooooooooooooooooo",
        "p": "None",
        "t": ""
      },
      {
        "c": "No",
        "d": "",
        "f": false,
        "l": "Personal",
        "n": "Get gloves for Niko",
        "o": "fooooooooooooooooooooooooo",
        "p": "None",
        "t": ""
      },
      {
        "c": "No",
        "d": "",
        "f": false,
        "l": "Personal",
        "n": "Get gloves for Niko",
        "o": "fooooooooooooooooooooooooo",
        "p": "None",
        "t": ""
      },
      {
        "c": "No",
        "d": "",
        "f": true,
        "l": "Personal",
        "n": "Get gloves for Niko",
        "o": "fooooooooooooooooooooooooo",
        "p": "None",
        "t": ""
      },
      {
        "c": "No",
        "d": "",
        "f": false,
        "l": "Personal",
        "n": "Get gloves for Niko",
        "o": "fooooooooooooooooooooooooo",
        "p": "None",
        "t": ""
      },
]

